name: PDF Converter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sundays
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      REACT_APP_AUTHOR: MayanMisfit
      REACT_APP_BUILD_DATE: '2025-03-19 13:58:28'
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Type check
        run: npx tsc --noEmit

      - name: Run tests
        run: npm test -- --passWithNoTests

      - name: Build project
        run: npm run build
        env:
          CI: true

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/
          retention-days: 7

  update-deps:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Update dependencies
        run: |
          npm update
          npm audit fix

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore(deps): update dependencies'
          title: 'chore(deps): update dependencies'
          body: |
            Auto-generated PR to update dependencies
            
            Last updated: 2025-03-19 13:58:28
            Updated by: MayanMisfit
          branch: update-deps
          base: main

  dependabot:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update Dependabot config
        run: |
          cat > .github/dependabot.yml << EOF
          version: 2
          updates:
            - package-ecosystem: "npm"
              directory: "/"
              schedule:
                interval: "weekly"
              open-pull-requests-limit: 10
              assignees:
                - "MayanMisfit"
              labels:
                - "dependencies"
                - "automated"
              commit-message:
                prefix: "chore"
                prefix-development: "chore"
                include: "scope"
          EOF

      - name: Commit Dependabot config
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update dependabot config"
          file_pattern: .github/dependabot.yml
